version: "3.1"

services:
  db:
    image: my_database
    container_name: "postgres"
    build:
      context: ./database/
    ports:
      - "5432:5432"
    networks:
      - my_network
    
  backend:
    image: my_backend
    container_name: "backend"
    build:
      context: ./backend/
    ports: 
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db

  frontend:
    image: my_frontend
    container_name: "frontend"
    build:
      context: ./frontend/
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - backend

networks:
  my_network:
    driver: bridge