spring:
  datasource:
    url: jdbc:postgresql://database:5432/uchain
    username: uchain
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
       ddl-auto: update